apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-h2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-h2
  template:
    metadata:
      labels:
        app: my-h2
    spec:
      containers:
        - name: my-h2
          image: jp.icr.io/t25-pham-ns/h2db:1.0
          imagePullPolicy: Always
          command:
          ports:
            - containerPort: 80
            